import requests
import json

#Short program to pull X and Y cooridnates from NYC Geoclient for mapping purposes

def xy_by_address(houseNum, street, borough):
	#These values are generated by NYC geocoder, to create an API account, go to:
	#https://api.cityofnewyork.us/geoclient/v1/doc
	#Once you have a user name and password, create a new project and generate an app_key and 
	#app_password    
	app_key = 'REDACTED'
    auth_key = 'REDACTED'
    call = 'https://api.cityofnewyork.us/geoclient/v1/address.json?houseNumber={}&street={}&borough={}&app_id={}&app_key={}'.format(houseNum, street, borough,app_key,auth_key)

    try:
        response = requests.get(call)

        if response.status_code == 200:
            data = response.json()
            return (data['address']['latitude'], data['address']['longitude'])
        else:
            return (0,0)

    except:
        ValueError("Unknown location")

def xy_by_intersection(crossStreet1, crossStreet2, borough):
	#These values are generated by NYC geocoder, to create an API account, go to:
	#https://api.cityofnewyork.us/geoclient/v1/doc
	#Once you have a user name and password, create a new project and generate an app_key and 
	#app_password    
	app_key = 'REDACTED'
    auth_key = 'REDACTED'
    call = 'https://api.cityofnewyork.us/geoclient/v1/intersection.json?crossStreetOne={}&crossStreetTwo={}&borough={}&boroughCrossStreetTwo={}&app_id={}&app_key={}'.format(crossStreet1, crossStreet2, borough, borough, app_key,auth_key)
    
    try:
        #Send our call to the server:
        response = requests.get(call)

        if response.status_code == 200:
            data = response.json()
            return data['intersection']['latitude'], data['intersection']['longitude']
        else:
            (0,0)

    except:
        ValueError("Unknown location")
    
